Moving Linux automatic builds to AppVeyor. Disabled build and upload of the Debug versions. Added Linux builds as AppVeyor artifacts. Preparing Travis-CI to run Coverity scans. Fixed Linux compilation error.

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -1,21 +1,34 @@
-image: Visual Studio 2017
+# Do not build on tags (GitHub only)
+skip_tags: true
 
-# version format
-version: 0.56.4.{build}
+# Do not increment the current build number after each automatic build
+#pull_requests:
+#  do_not_increment_build_number: true
 
-# branches to build
+# Branches to build
 branches:
   only:
     - master
 
-# Do not build on tags (GitHub only)
-skip_tags: true
+# Version format
+version: 1.1.0.{build}
+    
+image:
+  - Visual Studio 2017
+  - Ubuntu
 
 # Environmental variables
 environment:
-  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
-  CMAKE_GEN_32: Visual Studio 15 2017
-  CMAKE_GEN_64: Visual Studio 15 2017 Win64
+  matrix:
+    - # Windows
+      MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
+      CMAKE_GEN_32: Visual Studio 15 2017 
+      CMAKE_GEN_64: Visual Studio 15 2017 Win64
+    - # Linux
+      CMAKE_GEN: Unix Makefiles
+      CMAKE_TCH_32: ../src/cmake/toolchains/Linux-GNU-32.cmake
+      CMAKE_TCH_64: ../src/cmake/toolchains/Linux-GNU-64.cmake
+  # Common
   BUILD_DIR_32: build-32
   BUILD_DIR_64: build-64
   FTP_USER:
@@ -25,50 +38,154 @@ environment:
   FTP_SERVER:
     secure: ypUVoKvq2e+1urlrXABB5r5XsWuxKXWmvlJpQEe4iNw=
 
-# to run your custom scripts instead of automatic MSBuild
-build_script:
-  - mkdir %BUILD_DIR_32% %BUILD_DIR_64%
-  - cd "%BUILD_DIR_64%"
 
-  - ECHO. && ECHO ** Starting to build 64 bits Nightly version && ECHO.
-  - cmake -G "%CMAKE_GEN_64%" ..\src
-  - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Nightly
-  - ECHO. && ECHO ** End of the compilation of the 64 bits Nightly version && ECHO.
+# Build scripts
+for:
 
-  # if we are testing a pull request, building only a version will be sufficient, so stop this script
-  - IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (appveyor exit)
+  - # Windows build
+    matrix:
+      only:
+        - image: Visual Studio 2017
 
-  - ECHO. && ECHO ** Starting to build 64 bits Debug version && ECHO.
-  - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Debug
-  - ECHO. && ECHO ** End of the compilation of the 64 bits Debug version && ECHO.
+    install:
+      # Report our building tools
+      - msbuild /version
+      - cmake --version
 
-  - cd "..\%BUILD_DIR_32%"
+    # Use our custom script instead of automatic MSBuild
+    build_script:    
+      - mkdir %BUILD_DIR_32% %BUILD_DIR_64%
+      - cd "%BUILD_DIR_64%"
 
-  - ECHO. && ECHO ** Starting to build 32 bits Nightly version && ECHO.
-  - cmake -G "%CMAKE_GEN_32%" ..\src
-  - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Nightly
-  - ECHO. && ECHO ** End of the compilation of the 32 bits Nightly version && ECHO.
+      - |
+        IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (
+          ECHO. && ECHO ** Starting to build 64 bits Nightly version to test the Pull Request && ECHO.
+        ) ELSE (
+          ECHO. $$ECHO ** Starting to build 64 bits Nightly version && ECHO.
+        )
+      - cmake -G "%CMAKE_GEN_64%" ..\src
+      - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Nightly
+      - ECHO. && ECHO ** End of the compilation of the 64 bits Nightly version && ECHO.
 
-  - ECHO. && ECHO ** Starting to build 32 bits Debug version && ECHO.
-  - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Debug
-  - ECHO. && ECHO ** End of the compilation of the 32 bits Debug version && ECHO.
+      # if we are testing a pull request, building only a version will be sufficient, so stop this script
+      - IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (appveyor exit)
 
-  - cd ..
+      - ECHO. && ECHO ** Starting to build 64 bits Debug version && ECHO.
+      - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Debug
+      - ECHO. && ECHO ** End of the compilation of the 64 bits Debug version && ECHO.
 
-after_build:
-  # if we are testing a pull request, we don't want to upload the build to the host
-  - IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (appveyor exit)
+      - cd "..\%BUILD_DIR_32%"
 
-  - ECHO ** Compilation done. Packing the files and uploading to SphereCommunity
-  - mkdir accounts logs save scripts
-  - 7z a SphereSvrX-win64-nightly.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_64%\bin64\Nightly\SphereSvrX64_nightly.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini" "%APPVEYOR_BUILD_FOLDER%\dlls\64\*.dll"
-  - 7z a SphereSvrX-win64-debug.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_64%\bin64\Debug\SphereSvrX64_debug.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini" "%APPVEYOR_BUILD_FOLDER%\dlls\64\*.dll"
-  - 7z a SphereSvrX-win32-nightly.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_32%\bin\Nightly\SphereSvrX32_nightly.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini" "%APPVEYOR_BUILD_FOLDER%\dlls\32\*.dll"
-  - 7z a SphereSvrX-win32-debug.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_32%\bin\Debug\SphereSvrX32_debug.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini" "%APPVEYOR_BUILD_FOLDER%\dlls\32\*.dll"
-  - curl -sST "{SphereSvrX-win64-nightly.zip,SphereSvrX-win64-debug.zip,SphereSvrX-win32-nightly.zip,SphereSvrX-win32-debug.zip}" -u %FTP_USER%:%FTP_PASSWORD% %FTP_SERVER%
+      - ECHO. && ECHO ** Starting to build 32 bits Nightly version && ECHO.
+      - cmake -G "%CMAKE_GEN_32%" ..\src
+      - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Nightly
+      - ECHO. && ECHO ** End of the compilation of the 32 bits Nightly version && ECHO.
 
-artifacts:
-  - path: SphereSvrX-win64-nightly.zip
-  - path: SphereSvrX-win64-debug.zip
-  - path: SphereSvrX-win32-nightly.zip
-  - path: SphereSvrX-win32-debug.zip
+      - ECHO. && ECHO ** Starting to build 32 bits Debug version && ECHO.
+      - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Debug
+      - ECHO. && ECHO ** End of the compilation of the 32 bits Debug version && ECHO.
+
+      - cd ..
+
+    after_build:
+      # if we are testing a pull request, we don't want to upload the build to the host
+      - IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (appveyor exit)
+
+      - ECHO ** Compilation done. Packing the files and uploading to SphereCommunity
+      - mkdir accounts logs save scripts
+      - 7z a SphereSvrX-win64-nightly.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_64%\bin64\Nightly\SphereSvrX64_nightly.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini" "%APPVEYOR_BUILD_FOLDER%\dlls\64\*.dll"
+      - 7z a SphereSvrX-win64-debug.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_64%\bin64\Debug\SphereSvrX64_debug.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini" "%APPVEYOR_BUILD_FOLDER%\dlls\64\*.dll"
+      - 7z a SphereSvrX-win32-nightly.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_32%\bin\Nightly\SphereSvrX32_nightly.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini" "%APPVEYOR_BUILD_FOLDER%\dlls\32\*.dll"
+      - 7z a SphereSvrX-win32-debug.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_32%\bin\Debug\SphereSvrX32_debug.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini" "%APPVEYOR_BUILD_FOLDER%\dlls\32\*.dll"
+      - curl -sST "{SphereSvrX-win64-nightly.zip,SphereSvrX-win64-debug.zip,SphereSvrX-win32-nightly.zip,SphereSvrX-win32-debug.zip}" -u %FTP_USER%:%FTP_PASSWORD% %FTP_SERVER%
+
+    artifacts:
+      - path: SphereSvrX-win64-nightly.zip
+      - path: SphereSvrX-win32-nightly.zip
+
+
+  - # Linux build
+    matrix:
+      only:
+        - image: Ubuntu
+
+    install:
+      - echo && echo "** Setting up GCC compiler" && echo
+      - sudo apt install -qq --no-install-recommends gcc-7 gcc-7-multilib g++-7 g++-7-multilib
+      - export CC="gcc-7" && export CXX="g++-7"
+
+      # Report our building tools
+      - lsb_release -d
+      - gcc --version
+      - cmake --version
+
+    # Use our custom script
+    build_script:
+      - echo && echo "** Setting up MySQL development packages for 64 bits" && echo
+      - sudo apt install -qq --no-install-recommends curl libmysql++3 libmysqlclient-dev
+
+      - mkdir "$BUILD_DIR_32" "$BUILD_DIR_64"
+      - cd "$BUILD_DIR_64"
+
+      - |
+        if [ -n "${APPVEYOR_PULL_REQUEST_NUMBER}" ]; then
+          echo && echo "** Starting to build 64 bits Nightly version to test the Pull Request" && echo
+        else
+          echo && echo "** Starting to build 64 bits Nightly version" && echo
+        fi
+      - cmake -G "$CMAKE_GEN" -DCMAKE_BUILD_TYPE="Nightly" -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TCH_64" ../src
+      - make -j4 || exit 1  # if the build fails, stop here
+      - echo && echo "** End of the compilation of the 64 bits Nightly version" && echo
+
+      # if we are testing a pull request, building only a version will be sufficient, so stop this script
+      - |
+        if [ -n "${APPVEYOR_PULL_REQUEST_NUMBER}" ]; then
+          exit 0
+        fi
+
+      - echo && echo "** Starting to build 64 bits Debug version" && echo
+      - cmake -G "$CMAKE_GEN" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TCH_64" ../src
+      - make -j4 || exit 1  # if the build fails, stop here
+      - echo && echo "** End of the compilation of the 64 bits Debug version" && echo
+
+      - cd ..
+
+      - echo && echo "** Setting up MySQL development packages for 32 bits" && echo
+      - sudo apt-mark hold oracle-java8-installer oracle-java9-installer
+      - sudo apt remove -qq libmysql++3 libmysqlclient-dev
+      - sudo apt install -qq --no-install-recommends libmysql++3:i386 libmysqlclient-dev:i386
+      - export CC="gcc-7" && export CXX="g++-7"
+
+      - cd "$BUILD_DIR_32"
+
+      - echo && echo "** Starting to build 32 bits Nightly version" && echo
+      - cmake -G "$CMAKE_GEN" -DCMAKE_BUILD_TYPE="Nightly" -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TCH_32" ../src
+      - make -j4 || exit 1  # if the build fails, stop here
+      - echo && echo "** End of the compilation of the 32 bits Nightly version" && echo
+
+      - echo && echo "** Starting to build 32 bits Debug version" && echo
+      - cmake -G "$CMAKE_GEN" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TCH_32" ../src
+      - make -j4 || exit 1  # if the build fails, stop here
+      - echo && echo "** End of the compilation of the 32 bits Debug version" && echo
+
+      - cd ..
+
+    after_build:
+      # if we are testing a pull request, we don't want to upload the build to the host
+      - if [ -n "${APPVEYOR_PULL_REQUEST_NUMBER}" ]; then
+          exit 0
+        fi
+      - echo && echo "** Compilation done. Packing the files and uploading to SphereCommunity" && echo
+      - mkdir accounts logs save scripts
+      - tar -czf SphereSvrX-linux64-nightly.tar.gz accounts/ logs/ save/ scripts/ "${BUILD_DIR_64}/bin64/SphereSvrX64_nightly" -C src/ sphere.ini sphereCrypt.ini
+      - tar -czf SphereSvrX-linux64-debug.tar.gz accounts/ logs/ save/ scripts/ "${BUILD_DIR_64}/bin64/SphereSvrX64_debug" -C src/ sphere.ini sphereCrypt.ini
+      - tar -czf SphereSvrX-linux32-nightly.tar.gz accounts/ logs/ save/ scripts/ "${BUILD_DIR_32}/bin/SphereSvrX32_nightly" -C src/ sphere.ini sphereCrypt.ini
+      - tar -czf SphereSvrX-linux32-debug.tar.gz accounts/ logs/ save/ scripts/ "${BUILD_DIR_32}/bin/SphereSvrX32_debug" -C src/ sphere.ini sphereCrypt.ini
+      - curl -sST SphereSvrX-linux64-nightly.tar.gz -u ${FTP_USER}:${FTP_PASSWORD} ${FTP_SERVER}
+      - curl -sST SphereSvrX-linux64-debug.tar.gz -u ${FTP_USER}:${FTP_PASSWORD} ${FTP_SERVER}
+      - curl -sST SphereSvrX-linux32-nightly.tar.gz -u ${FTP_USER}:${FTP_PASSWORD} ${FTP_SERVER}
+      - curl -sST SphereSvrX-linux32-debug.tar.gz -u ${FTP_USER}:${FTP_PASSWORD} ${FTP_SERVER}
+
+    artifacts:
+      - path: SphereSvrX-linux64-nightly.zip
+      - path: SphereSvrX-linux32-nightly.zip
